configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YTU2MDUwNTVmMGQ4YjZmYzI2YTFmOTcwMTMyMGQyNTJiMjgzZDFkMDNlOTE4MDcwODg0ODg5MzRkYjcxZDZhNzFjNWU1NjY5OTliZDIyNzBjYTdiOWEzMjhlZTg3MjE2NTBiZWIzZWE1MDZjMjY2NGFhZmU2ZmIwZTc2ODgzYjA=
