name: gateway
services:
  mysql:
    image: mysql:8.4.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=gateway
    ports:
      - "3306:3306"
    command: >
      mysqld --lower_case_table_names=1
             --skip-mysqlx
             --character_set_server=utf8mb4
             --explicit_defaults_for_timestamp
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -psecret -e 'SHOW DATABASES;'"]
      interval: 5s
      timeout: 10s
      retries: 10
